// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "There are no terms of service. We accept no responsibility for your ignorance.",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/leaderboard": {
            "get": {
                "description": "Get the leaderboards for a specifc discord server ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "summary": "Get leaderboard data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Leaderboard"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/lookup/{srv}/{usr}": {
            "get": {
                "description": "Gets the users account information by their Username and Server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Riot"
                ],
                "summary": "Show an account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Riot Server",
                        "name": "srv",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "usr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LookupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/match/{srv}/{usr}": {
            "get": {
                "description": "Show the past 10 matches",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Riot"
                ],
                "summary": "Show recent matches",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Riot Server",
                        "name": "srv",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "usr",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "count",
                        "name": "usr",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.MatchDataResp"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/ping": {
            "get": {
                "description": "Ping the API service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utility"
                ],
                "summary": "Pings the API service to ensure that it is active",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/v1/user": {
            "post": {
                "description": "Creates and stores the users data to be used when executing commands/api calls.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Create an account",
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/user/{id}": {
            "get": {
                "description": "Looks up a users profile to display which servers they are part of in addidion to their stored riot account information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Look up a profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserLookupResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "Updates the users profile.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Update a profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "409": {
                        "description": "Conflict"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "Deletes the users profile by supplying the discord id in the path along with the server ID as a URL param.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Delete a profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "string serverid",
                        "name": "discordID",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ChampionMasteryResp": {
            "type": "object",
            "properties": {
                "championId": {
                    "type": "integer"
                },
                "championLevel": {
                    "type": "integer"
                },
                "championName": {
                    "type": "string"
                },
                "championPoints": {
                    "type": "integer"
                }
            }
        },
        "models.Leaderboard": {
            "type": "object",
            "properties": {
                "currentObjective": {
                    "type": "string"
                },
                "discordServerID": {
                    "type": "string"
                },
                "leaders": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Leaders"
                    }
                },
                "secTillNextObj": {
                    "type": "integer"
                }
            }
        },
        "models.Leaders": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer"
                },
                "score": {
                    "type": "string"
                },
                "summonerName": {
                    "type": "string"
                }
            }
        },
        "models.LookupResponse": {
            "type": "object",
            "properties": {
                "champions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ChampionMasteryResp"
                    }
                },
                "level": {
                    "type": "integer"
                },
                "losses": {
                    "type": "integer"
                },
                "profileIconId": {
                    "type": "integer"
                },
                "rank": {
                    "type": "string"
                },
                "tier": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "wins": {
                    "type": "integer"
                }
            }
        },
        "models.MatchDataResp": {
            "type": "object",
            "properties": {
                "assists": {
                    "type": "integer"
                },
                "championName": {
                    "type": "string"
                },
                "deaths": {
                    "type": "integer"
                },
                "gameID": {
                    "type": "string"
                },
                "gameMode": {
                    "type": "string"
                },
                "kills": {
                    "type": "integer"
                },
                "win": {
                    "type": "boolean"
                }
            }
        },
        "models.UserLookupResponse": {
            "type": "object",
            "properties": {
                "riotServer": {
                    "type": "string"
                },
                "riotUsername": {
                    "type": "string"
                },
                "servers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.LoLQueue.com",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "LoLQueue API",
	Description:      "This is the documentation for the LoLQueue Api Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
